language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  include:
    - rust: 1.26.0 # lock down for consistent rustfmt behavior
      env: RUSTFMT
      install:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --write-mode=diff
  allow_failures:
    - rust: nightly

# copied from https://github.com/dnaq/sodiumoxide/blob/master/.travis.yml
install:
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.15/libsodium-1.0.15.tar.gz
  - tar xvfz libsodium-1.0.15.tar.gz
  - cd libsodium-1.0.15 && ./configure --prefix=$HOME/installed_libsodium && make && make install && cd ..
  - export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH

script:
  - cargo clean
  - cargo build --verbose --all
#  - cargo run --verbose --example XYZ
#  - cargo test --verbose --features "test" --all
  - cargo test --verbose --all

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
