language: rust

addons:
  apt:
    packages:
      - libssl-dev
cache: cargo

rust:
  - stable
  - beta
  - nightly

branches:
  except:
    - /^WIP-.*$/

matrix:
  include:
    - rust: 1.31.0 # lock down for consistent rustfmt behavior
      env: RUSTFMT
      install:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --check
    - rust: 1.31.0
      env: CLIPPY
      install:
        - rustup component add clippy
      script:
        - cargo clippy
  allow_failures:
    - rust: nightly # both compiles and clippy

script:
  - cargo clean
  - cargo build --verbose --all
  - cargo test --verbose --all

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin &&
    cargo tarpaulin --no-count --skip-clean --out Xml &&
    bash <(curl -s https://codecov.io/bash)
  fi
