language: rust

rust:
  - stable
  - beta
  - nightly

branches:
  except:
    - /^WIP-.*$/

matrix:
  include:
    - rust: 1.31.0 # lock down for consistent rustfmt behavior
      env: RUSTFMT
      install:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --check
    - rust: stable
      env: CLIPPY
      install:
        - rustup component add clippy-preview
      script:
        - cargo clippy
  allow_failures:
    - rust: nightly # both compiles and clippy

script:
  - cargo clean
  - cargo build --verbose --all
#  - cargo run --verbose --example XYZ
#  - cargo test --verbose --features "test" --all
  - cargo test --verbose --all

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
