language: rust

addons:
  apt:
    packages:
      - libssl-dev
cache: cargo

rust:
  - stable
  - beta
  - nightly

branches:
  except:
    - /^WIP-.*$/

matrix:
  include:
    - rust: 1.31.0 # lock down for consistent rustfmt behavior
      env: RUSTFMT
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - rust: 1.31.0
      env: CLIPPY
      install:
        - rustup component add clippy
      script:
        - cargo clippy
  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

script:
  - cargo clean
  - cargo build --verbose --all
  - cargo test --verbose --all

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
