language: rust

addons:
  apt:
    packages:
      - libssl-dev

#cache: cargo
# cache less, per https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo

rust:
  - stable
  - beta
  - 1.36.0
  - nightly

branches:
  except:
    - /^WIP-.*$/

matrix:
  include:
    - rust: 1.36.0 # lock down for consistent rustfmt behavior
      env: RUSTFMT
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - rust: 1.36.0
      env: CLIPPY
      install:
        - rustup component add clippy
      script:
        - cargo clippy
  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi
  rm -rf /home/travis/.cargo/registry

script:
  - cargo clean
  - cargo build --verbose --all
  - cargo test --verbose --all

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
