[package]
name = "magic-wormhole"
version = "0.3.1"
authors = [
    "piegames <info@piegames.de>",
    "Brian Warner <warner@lothar.com>"
]
description = "Get things from one computer to another, safely"
keywords = ["magic-wormhole", "wormhole", "file-transfer", "transfer"]
categories = ["network-programming", "command-line-utilities"]
readme = "README.md"
homepage = "http://magic-wormhole.io/"
repository = "https://github.com/magic-wormhole/magic-wormhole.rs"
documentation = "https://docs.rs/magic-wormhole/latest/"
license = "EUPL-1.2"
edition = "2021"
rust-version = "1.59" # MSRV

[dependencies]
serde = { version = "1.0.120", features = ["rc"] }
serde_json = "1.0.61"
serde_derive = "1.0.120"
xsalsa20poly1305 = "0.8.0"
spake2 = "0.3.1"
sha-1 = "0.10.0"
sha2 = "0.10.0"
hkdf = "0.12.2"
hex = { version = "0.4.2", features = ["serde"] }
rand = "0.8.3"
regex = "1.4.3"
log = "0.4.13"
# zeroize = { version = "1.2.0", features = ["zeroize_derive"] }
get_if_addrs = "0.5.3"
byteorder = "1.4.2"
base64 = "0.13.0"
futures_ringbuf = "0.3.1"
tar = "0.4.33"
time = { version = "0.3.7", features = ["formatting"] }

derive_more = { version = "0.99.0", default-features = false, features = ["display", "deref", "from"] }
thiserror = "1.0.24"

futures = "0.3.12"
async-std = { version = "1.11.0", features = ["attributes", "unstable"] }
async-tungstenite = { version = "0.17.1", features = ["async-std-runtime", "async-tls"] }
async-io = "1.6.0"
socket2 = "0.4.1"
libc = "0.2.101"
stun_codec = "0.2.0"
bytecodec = "0.4.15"
url = { version = "2.2.2", features = ["serde"] }
rmp-serde = "1.0.0"
http = "0.2.5"

# for some tests
[dev-dependencies]
env_logger = "0.9.0"
eyre = "0.6.5"

[profile.release]
overflow-checks = true
strip = "debuginfo"
lto = "thin"

[workspace]
members = [".", "cli"]
default-members = ["cli"]
