[workspace]
members = [
        "core",
#        "io/tokio",
        "io/blocking",
        "cli",
]

[badges]
travis-ci = { repository = "warner/magic-wormhole.rs" }


[profile.release]
overflow-checks = true
