[package]
name = "magic-wormhole"
version = "0.0.1"
authors = ["Brian Warner <warner@lothar.com>"]

[badges]
travis-ci = { repository = "warner/magic-wormhole.rs" }

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
sodiumoxide = "0.0.16"
spake2 = "0.1.0"
sha2 = "0.8"
hkdf = "0.7.0"
hex = "0.3"
rand = "0.5"
rustc-serialize = "0.3"
regex = "1.0"

# for "io_blocking" feature
ws = { version = "0.7.*", optional = true }
url = { version = "1.7", optional = true }

# for "io_tokio" feature
websocket = { version = "0.20", optional = true }
futures = { version = "0.1", optional = true }
tokio-core = { version = "0.1", optional = true }

[dev-dependencies]
ws = "0.7"
url = "1.7"
rustyline = "2.0"
parking_lot = {version = "0.6", features = ["deadlock_detection"]}
hex = "0.3"

[features]
default = ["io-blocking", "io-tokio"]
io-blocking = ["ws", "url"]
io-tokio = ["websocket", "futures", "tokio-core"]

[[bin]]
name = "wormhole"
path = "src/bin/main.rs"
required-features = ["io-blocking"]

[profile.release]
overflow-checks = true
