version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.35
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: install rustfmt and clippy
          command: |
            rustup component add rustfmt
            rustup component add clippy
      - run:
          name: cargo fmt
          command: cargo fmt -- --check
      - run:
          name: cargo build
          command: cargo build
      - run:
          name: cargo test
          command: cargo test
      - run:
          name: clippy
          command: cargo clippy
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
