version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.35
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Cargo Build
          command: cargo build
      - run:
          name: Cargo Test
          command: cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
